name: on pull request
on:
  pull_request:
    branches:
      - main

env:
  EM_VERSION: 3.1.72

jobs:
  check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check Lint and Format
        run: pnpm check

  build:
    needs: check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v5

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}

      - name: resolve git submodule
        run: git submodule update --init --recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: pnpm build:all
